base_url = "https://arechen.github.io/rustlings-cn"
title = "Rustlings 中文版"
description = "通过小练习熟悉 Rust 代码的阅读与编写！"

compile_sass = false
build_search_index = false

[markdown]
insert_anchor_links = "heading"

[markdown.highlighting]
theme = "dracula"

[extra]
logo_path = "images/happy_ferris.svg"

[[extra.menu_items]]
name = "首页"
url = "@/_index.md"
[[extra.menu_items]]
name = "安装"
url = "@/setup/index.md"
[[extra.menu_items]]
name = "使用"
url = "@/usage/index.md"
[[extra.menu_items]]
name = "社区练习"
url = "@/community-exercises/index.md"
[[extra.menu_items]]
name = "问答"
url = "https://github.com/rust-lang/rustlings/discussions/categories/q-a?discussions_q="

[[extra.footer_items]]
name = "代码仓库"
url = "https://github.com/AreChen/rustlings-cn"
[[extra.footer_items]]
name = "更新日志"
url = "https://github.com/AreChen/rustlings-cn/blob/main/CHANGELOG.md"
[[extra.footer_items]]
name = "MIT 许可证"
url = "https://github.com/AreChen/rustlings-cn/blob/main/LICENSE"
